apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: findit
  labels:
    app.kubernetes.io/name: findit
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - port: 5000
      targetPort: 5000
      name: http
