apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: findit
  labels:
    app.kubernetes.io/name: findit
    app.kubernetes.io/component: frontend
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
      name: http
