apiVersion: v1
kind: Secret
metadata:
  name: findit-secret
  namespace: findit
  labels:
    app.kubernetes.io/name: findit
type: Opaque
stringData:
  DB_USER: "postgres"
  DB_PASSWORD: "postgres_k8s_secure_2026"
  POSTGRES_PASSWORD: "postgres_k8s_secure_2026"
